version: '3.9'

services:
  frontend:
    container_name: socialmedia-front
    build:
      context: ./social_media
      dockerfile: ./Dockerfile
    volumes:
      - './social_media:/App'
      - '/App/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: socialmedia-back
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - "./server:/App"
      - "/App/node_modules"
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true